name: Terraform Apply

on: [push]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Terraform
      env:
        TERRAFORM_VERSION: "1.4.4"
      run: |
        rm -f terraform_*.zip
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TF_USER_AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_USER_AWS_SECRET }}
      run: terraform init -input=false

    - name: Terraform validation
      run: terraform validate
      
    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TF_USER_AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_USER_AWS_SECRET }}
        
      run: | 
        terraform import aws_glue_security_configuration.s3_encrypt_decrypt s3_encrypt_decrypt
        terraform import aws_s3_bucket.this dataengineeringrawglabdev
        terraform apply -auto-approve -input=false
